routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if(auth()->check())
    {
        return redirect('/home');
    } else {
        return redirect('login');
    }
});
Route::get('password/reset/{token}','Auth\ResetPasswordController@showResetForm')->name('register.reset');
Route::get('password/reset/','Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email','Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('register','Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register','Auth\RegisterController@register');
Route::get('login','Auth\LoginController@showLoginForm')->name('login');
Route::post('login','Auth\LoginController@login');


Route::group(['middleware' => ['auth']], function () {
    Route::get('dashboard','DashboardController@index')->name('dashboard.index');
    Route::get('getBentukUsaha','DashboardController@getBentukUsaha');
    Route::get('getKabupaten','DashboardController@getKabupaten');
    Route::get('getJmlAnggotaKoperasi','DashboardController@getJmlAnggotaKoperasi');
    Route::post('logout','Auth\LoginController@logout')->name('logout');
    Route::resource('koperasi','KoperasiController');
    Route::get('getAllKoperasi','KoperasiController@getAllKoperasi');
    Route::get('exportAllKoperasi','KoperasiController@exportAllKoperasi');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('jenis_koperasi','JenisKoperasiController');
    Route::get('role','ManagementUserController@formRole')->name('role');
    Route::post('role','ManagementUserController@addRole');
    Route::get('user','ManagementUserController@allUsers')->name('user');
    Route::get('user/create','ManagementUserController@createUser')->name('user.create');
    Route::post('user','ManagementUserController@storeUser')->name('user.store');
    Route::delete('user/{id}','ManagementUserController@destroyUser')->name('user.destroy');
    Route::get('user/{id}/edit','ManagementUserController@editUser')->name('user.edit');
    Route::put('user/{id}','ManagementUserController@updateUser')->name('user.update');
    Route::get('file/create','FileController@createFileKoperasi');
    Route::post('file','FileController@storeFile')->name('file.store');
    Route::get('file/{id}','FileController@showFileKoperasi')->name('fileKoperasi.show');
    Route::delete('file/{id}','FileController@destroyFileKoperasi')->name('fileKoperasi.destroy');
    Route::get('file/{id}/edit','FileController@editFileKoperasi');
    Route::put('file/{id}','FileController@updateFileKoperasi');
    Route::get('all_koperasi','KoperasiController@allKoperasi')->name('all.koperasi');
    Route::get('export_bap_word/{id}','KoperasiController@exportWord')->name('koperasi.exportWord');
    Route::get('form_spk/{id}','KoperasiController@formSpk')->name('koperasi.formSpk');
    Route::post('export_spk/{id}','KoperasiController@exportSpk')->name('koperasi.exportSpk');
    Route::get('getKota/{id}','IndonesianZoneController@getKota');
    Route::get('getKecamatan/{id}','IndonesianZoneController@getKecamatan');
    Route::get('getKelurahan/{id}','IndonesianZoneController@getKelurahan');    
});

app/Http/Controllers/KoperasiController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\KoperasiModel;
use App\JenisKoperasiModel;
use App\BentukUsahaModel;
use App\JenisUsahaModel;
use App\KelompokUsahaModel;
use App\SektorUsahaModel;
use App\RekapFileModel;
use App\KotaModel;
use App\KecamatanModel;
use App\KelurahanModel;
use Auth;
use File;
use Carbon\Carbon;
use App\ProvinsiModel;
use Terbilang;
use DataTables;
use DB;
use App\Exports\KoperasiExport;
use Maatwebsite\Excel\Facades\Excel;

class KoperasiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function uniqueFilename($path, $name, $ext) {
	
        $output = $name;
        $basename = basename($name, '.' . $ext);
        $i = 2;
        
        while(File::exists($path . '/' . $output)) {
            $output = $basename . $i . '.' . $ext;
            $i ++;
        }
        
        return $output;
        
    }
    public function index()
    {
        $jenisKoperasi = JenisKoperasiModel::all();
        return view('admin.koperasi.index',['jenisKoperasi' => $jenisKoperasi]);
    }
    public function allKoperasi()
    {
        // $koperasi = KoperasiModel::with(['jenis','provinsi','kabupaten']);
        // return view('admin.koperasi.allKoperasi',['koperasi' => $koperasi]);
        return view('admin.koperasi.allKoperasi');
    }
    public function getAllKoperasi() {
        $koperasi = KoperasiModel::with(['provinsi','kabupaten','jenis'])->orderBy('created_at','ASC');
        return Datatables::of($koperasi)
        ->addColumn('action',function($item){
            return view('admin.koperasi.buttonAllKoperasi',['item' => $item])->render();
        })
        ->make(true);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $jenisKoperasi = JenisKoperasiModel::all();
        $bentukUsahaModel = BentukUsahaModel::all();
        $jenisUsahaModel = JenisUsahaModel::all();
        $kelompokUsahaModel = KelompokUsahaModel::all();
        $sektorUsahaModel = SektorUsahaModel::all();
        $provinsi = ProvinsiModel::all();
        return view('admin.koperasi.create',[
            'jenisKoperasi' => $jenisKoperasi,
            'bentukUsahaModel' => $bentukUsahaModel,
            'jenisUsahaModel' => $jenisUsahaModel,
            'kelompokUsahaModel' => $kelompokUsahaModel,
            'sektorUsahaModel' => $sektorUsahaModel,
            'provinsi' => $provinsi
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {            
            $koperasi = new KoperasiModel;
            $koperasi->jenis_id = $request->input('jenis_id');
            $koperasi->users_id = Auth::user()->id;
            $koperasi->sektor_usaha_id = $request->input('sektor_usaha_id');
            $koperasi->bentuk_usaha_id = $request->input('bentuk_usaha_id');
            $koperasi->kelompok_usaha_id = $request->input('kelompok_usaha_id');
            $koperasi->jenis_usaha_id = $request->input('jenis_usaha_id');
            $koperasi->provinsi_id = $request->input('provinsi_id');
            $koperasi->kabupaten_id = $request->input('kabupaten_id');
            $koperasi->kecamatan_id = $request->input('kecamatan_id');
            $koperasi->kelurahan_id = $request->input('kelurahan_id');
            $koperasi->nomor_spk = $request->input('nomor_spk');
            $koperasi->tgl_spk = $request->input('tgl_spk');
            $koperasi->nama_institusi = $request->input('nama_institusi');
            $koperasi->nomor_badan_hukum_awal = $request->input('nomor_badan_hukum_awal');
            $koperasi->nomor_badan_hukum_akhir = $request->input('nomor_badan_hukum_akhir');
            $koperasi->nama_ketua = $request->input('nama_ketua');
            $koperasi->alamat = $request->input('alamat');
            $koperasi->jml_anggota = $request->input('jml_anggota');            
            $koperasi->biaya_hosting = $request->input('biaya_hosting');
            $koperasi->pic_teknik = $request->input('pic_teknik');
            $koperasi->no_telp = $request->input('no_telp');
            $koperasi->email = $request->input('email');
            $koperasi->url = $request->input('url');
            $koperasi->syariah = $request->input('syariah');
            $koperasi->level = $request->input('level');
            $koperasi->status = $request->input('status');
            $koperasi->tgl_setup = $request->input('tgl_setup');
            $koperasi->harga_aplikasi = $request->input('harga_aplikasi');
            $koperasi->history = $request->input('history');
            $koperasi->status_pembayaran = $request->input('status_pembayaran');
            $koperasi->save();
            
            return redirect('koperasi')->with('success','Data Berhasil di Masukan');
        } catch (\Exception $e) {
            return back()->with('danger', $e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $jenisKoperasi = JenisKoperasiModel::with(['koperasi','users'])->findOrFail($id);        
        return view('admin.koperasi.show',['jenisKoperasi' => $jenisKoperasi]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $provinsi = ProvinsiModel::all();
        $bentukUsahaModel = BentukUsahaModel::all();
        $jenisUsahaModel = JenisUsahaModel::all();
        $kelompokUsahaModel = KelompokUsahaModel::all();
        $sektorUsahaModel = SektorUsahaModel::all();
        $koperasi = KoperasiModel::with(['jenis','rekap_file','bentukUsaha','jenisUsaha','kelompokUsaha','sektorUsaha','provinsi','kabupaten','kecamatan','kelurahan'])->findOrFail($id);
        $kabupaten = KotaModel::where('provinsi_id', $koperasi->provinsi->id)->get();        
        $kecamatan = KecamatanModel::where('kabupaten_id', $koperasi->kabupaten->id)->get();        
        if($koperasi->kecamatan == null)
        {
            $kelurahan = KelurahanModel::all();
        } else {
            $kelurahan = KelurahanModel::where('kecamatan_id', $koperasi->kecamatan->id)->get();
        }
        $jenis = JenisKoperasiModel::all();

        return view('admin.koperasi.edit',[
            'provinsi' => $provinsi,
            'kabupaten' => $kabupaten,
            'kecamatan' => $kecamatan,
            'kelurahan' => $kelurahan,
            'koperasi' => $koperasi,
            'jenis' => $jenis,
            'bentukUsahaModel' => $bentukUsahaModel,
            'jenisUsahaModel' => $jenisUsahaModel,
            'kelompokUsahaModel' => $kelompokUsahaModel,
            'sektorUsahaModel'=> $sektorUsahaModel
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {        
        try {
            $koperasi = KoperasiModel::with('jenis')->findOrFail($id);
            $koperasi->jenis_id = $request->input('jenis_id');
            $koperasi->users_id = Auth::user()->id;
            $koperasi->sektor_usaha_id = $request->input('sektor_usaha_id');
            $koperasi->bentuk_usaha_id = $request->input('bentuk_usaha_id');
            $koperasi->kelompok_usaha_id = $request->input('kelompok_usaha_id');
            $koperasi->jenis_usaha_id = $request->input('jenis_usaha_id');
            $koperasi->provinsi_id = $request->input('provinsi_id');
            $koperasi->kabupaten_id = $request->input('kabupaten_id');
            $koperasi->kecamatan_id = $request->input('kecamatan_id');
            $koperasi->kelurahan_id = $request->input('kelurahan_id');
            $koperasi->nomor_spk = $request->input('nomor_spk');
            $koperasi->tgl_spk = $request->input('tgl_spk');
            $koperasi->nama_institusi = $request->input('nama_institusi');
            $koperasi->nama_ketua = $request->input('nama_ketua');
            $koperasi->alamat = $request->input('alamat');
            $koperasi->jml_anggota = $request->input('jml_anggota');
            $koperasi->biaya_hosting = $request->input('biaya_hosting');            
            $koperasi->pic_teknik = $request->input('pic_teknik');    
            $koperasi->no_telp = $request->input('no_telp');
            $koperasi->email = $request->input('email');
            $koperasi->url = $request->input('url');
            $koperasi->syariah = $request->input('syariah');
            $koperasi->level = $request->input('level');
            $koperasi->status = $request->input('status');            
            $koperasi->tgl_setup = $request->input('tgl_setup');
            $koperasi->harga_aplikasi = $request->input('harga_aplikasi');
            $koperasi->history = $request->input('history');
            $koperasi->status_pembayaran = $request->input('status_pembayaran');

            $koperasi->save();

            return redirect('koperasi/'.$koperasi->jenis->id)->with('success', 'Data Berhasil di Perbaharui');         
        } catch (\Exception $e) {
            return back()->with('danger', $e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $koperasi = KoperasiModel::with('rekap_file')->findOrFail($id);
            foreach($koperasi->rekap_file as $value)
            {

resources/views/admin/koperasi/buttonAllKoperasi.blade.php
<td>
  <div class="section__action">
    <div class="list__section__action">
  <a href="#" class="btn m-btn btn-primary btn-sm m-btn--icon m-btn--pill m-btn--air icon-only">
  <span>
    <i class="la la-eye"></i>
    <span>Profil Koperasi</span>
  </span>
  </a>
  <a href="javascript:void(0);" onclick="$(this).find('form').submit();" class="btn m-btn btn-outline-danger btn-sm  m-btn--icon m-btn--pill icon-only m_sweetalert_5" title="Delete Koperasi">
    <span>
      <i class="la la-trash"></i>
      <span>Delete Koperasi</span>                
    </span>
    <form action="{{ route('koperasi.destroy', $item->id) }}" method="post">
      {{ csrf_field() }}
      {{ method_field('DELETE') }}
    </form>
  </a>
  <a href="{{ url('koperasi/'.$item->id.'/edit')}}" class="btn m-btn btn-success btn-sm m-btn--icon m-btn--pill icon-only" title="Edit Koperasi">
    <span>
      <i class="la la-pencil"></i>
      <span>Edit Koperasi</span>
    </span>
  </a>                  
  <a href="{{ url('file/'.$item->id) }}" class="btn m-btn btn-info btn-sm m-btn--icon m-btn--pill m-btn--air icon-only m--margin-top-5" title="Management File">
    <span>
      <i class="la la-file"></i>
      <span>Management File</span>
    </span>
  </a>
  <a href="{{ url('export_bap_word/'.$item->id) }}" class="btn m-btn btn-warning btn-sm m-btn--icon m-btn--pill m-btn--air icon-only m--margin-top-5" title="Export Word BAP">
    <span>
        <i class="la la-print"></i>
      <span>Export BAP</span>
    </span>
  </a>
  <a href="{{ url('form_spk/'.$item->id) }}" class="btn m-btn btn-secondary btn-sm m-btn--icon m-btn--pill m-btn--air icon-only m--margin-top-5" title="Export Word SPK">
    <span>
        <i class="la la-print"></i>
      <span>Export SPK</span>
    </span>
  </a>
</td>

resources/views/admin/koperasi/create.blade.php
@extends('layouts.app')
@section('title')
    Tambah Koperasi
@endsection
@section('headerPage')
    Tambah Koperasi
@endsection
@section('isi')
@if ($errors->any())    
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
@if(session()->has('success'))
<div class="m-alert m-alert--icon alert m-alert--square alert-success m--margin-bottom-25" role="alert">
    <div class="m-alert__icon">
        <i class="la la-check-circle-o"></i>
    </div>
    <div class="m-alert__text">
        <strong>Berhasil!</strong> {{ session()->get('success') }}
    </div>
    <div class="m-alert__close">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        </button>
    </div>
</div>
@endif
@if(session()->has('danger'))
<div class="m-alert m-alert--icon alert m-alert--square alert-danger m--margin-bottom-25" role="alert">
    <div class="m-alert__icon">
        <i class="la la-exclamation-circle"></i>
    </div>
    <div class="m-alert__text">
        <strong>Gagal!</strong> {{ session()->get('danger') }}
    </div>
    <div class="m-alert__close">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        </button>
    </div>
</div>
@endif
<form method="POST" action="{{route('koperasi.store')}}">
    {{ csrf_field() }}
    <div class="form-group m-form__group">
        <label for="Nama">Provinsi</label>
        <div class="m-form__control">
            <select class="form-control m-select2 m_select2_4" name="provinsi_id">
                <option value="">- Pilih Provinsi -</option>
                @foreach ($provinsi as $item)
                    <option value="{{$item->id}}">{{ $item->name }}</option>
                @endforeach
            </select>
        </div>
        <span class="m-form__help">Tolong Pilih dan Sesuaikan</span>
    </div>
    <div class="form-group m-form__group">
        <label for="Nama">Kota</label>
        <div class="m-form__control">
            <select class="form-control m-select2 m_select2_4" name="kabupaten_id" id="kabupaten_id">
                <option value="">- Pilih Kabupaten -</option>
            </select>
        </div>
        <span class="m-form__help">Tolong Pilih dan Sesuaikan</span>
    </div>
    <div class="form-group m-form__group">
        <label for="Nama">Kecamatan</label>
        <div class="m-form__control">
            <select class="form-control m-select2 m_select2_4" name="kecamatan_id" id="kecamatan_id">
                <option value="">- Pilih Kecamatan -</option>
            </select>
        </div>
        <span class="m-form__help">Tolong Pilih dan Sesuaikan</span>
    </div>
    <div class="form-group m-form__group">
        <label for="Nama">Kelurahan</label>
        <div class="m-form__control">
            <select class="form-control m-select2 m_select2_4" name="kelurahan_id">
                <option value="">- Pilih Kelurahan -</option>
            </select>
        </div>
        <span class="m-form__help">Tolong Pilih dan Sesuaikan</span>
    </div>
    <div class="form-group">
        <label>Nama Koperasi</label>
        <input type="name" class="form-control" name="nama_institusi" placeholder="Masukan Nama Koperasi">
    </div>
    <div class="form-group">
        <label>Nomor Badan Hukum Awal</label>
        <input type="name" class="form-control" name="nomor_badan_hukum_awal" placeholder="Masukan Nomor Badan Hukum Awal">
    </div>
    <div class="form-group">
        <label>Nomor Badan Hukum Akhir</label>
        <input type="name" class="form-control" name="nomor_badan_hukum_akhir" placeholder="Masukan Nomor Badan Hukum Akhir">
    </div>
    <div class="form-group">
        <label class="form-control-label">Tanggal SPK</label>                
        <div class="input-group m-input-group">
            <input type="text" name="tgl_spk" class="form-control" id="m_datepicker_1" readonly="" placeholder="Select date &amp; time">
            <div class="input-group-prepend"><span class="input-group-text"><i class="la la-calendar-check-o"></i></span></div>
        </div>
    </div>
    <div class="form-group">
        <label for="">Alamat</label>
        <textarea name="alamat" cols="30" rows="10" class="form-control" placeholder="Masukan Alamat"></textarea>
    </div>
    <div class="form-group">
        <label>Nomor Telepon PIC Teknik</label>
        <input type="number" class="form-control" name="no_telp" placeholder="Masukan Nomor Telepon">
    </div>
    <div class="form-group">
        <label>Email PIC Teknik</label>
        <input type="email" class="form-control" name="email" placeholder="Masukan Email">        
    </div>
    <div class="form-group">
        <label>Website</label>
        <input type="url" class="form-control" name="url" placeholder="Masukan URL">
        <span class="m-form__help">Contoh : https://koperasidomain.com</span>
    </div>
    <div class="form-group m-form__group">
        <label for="Nama">Sektor Usaha</label>
        <div class="m-form__control">
            <select class="form-control m-select2 m_select2_4" name="sektor_usaha_id">
                    <option value="">- Pilih Sektor Usaha -</option>
                @foreach ($sektorUsahaModel as $item)
                    <option value="{{$item->id}}">{{ $item->nama }}</option>
                @endforeach
            </select>
        </div>
        <span class="m-form__help">Tolong Pilih dan Sesuaikan</span>
    </div>
    <div class="form-group m-form__group">
        <label for="Nama">Bentuk Usaha</label>
        <div class="m-form__control">
            <select class="form-control m-select2 m_select2_4" name="bentuk_usaha_id">
                    <option value="">- Pilih Bentuk Usaha -</option>
                @foreach ($bentukUsahaModel as $item)
                    <option value="{{$item->id}}">{{ $item->nama }}</option>
                @endforeach
            </select>
        </div>
        <span class="m-form__help">Tolong Pilih dan Sesuaikan</span>
    </div>
    <div class="form-group m-form__group">
        <label for="Nama">Kelompok Usaha</label>
        <div class="m-form__control">
            <select class="form-control m-select2 m_select2_4" name="kelompok_usaha_id">
                    <option value="">- Pilih Kelompok Usaha -</option>
                @foreach ($kelompokUsahaModel as $item)
                    <option value="{{$item->id}}">{{ $item->nama }}</option>
                @endforeach
            </select>
        </div>
        <span class="m-form__help">Tolong Pilih dan Sesuaikan</span>
    </div>
    <div class="form-group m-form__group">
        <label for="Nama">Jenis Usaha</label>
        <div class="m-form__control">
            <select class="form-control m-select2 m_select2_4" name="jenis_usaha_id">
                    <option value="">- Pilih Jenis Usaha -</option>
                @foreach ($jenisUsahaModel as $item)
                    <option value="{{$item->id}}">{{ $item->nama }}</option>
                @endforeach
            </select>
        </div>
        <span class="m-form__help">Tolong Pilih dan Sesuaikan</span>
    </div>
    <div class="form-group">
        <label>Jenis Koperasi</label>
        <select name="jenis_id" class="form-control select2 m_select2_4">                
            @foreach ($jenisKoperasi as $item)
            <option value="{{$item->id}}">{{$item->nama}}</option>
            @endforeach
        </select>
    </div>
    <div class="form-group">
        <label>Nomor SPK</label>
        <input type="name" class="form-control" name="nomor_spk" placeholder="Masukan Nomor SPK">
    </div>
    <div class="form-group">
        <label>Nama Ketua</label>
        <input type="name" class="form-control" name="nama_ketua" placeholder="Masukan Nama Ketua">
    </div>        
    <div class="form-group">
        <label>Jumlah Anggota</label>
        <input type="number" class="form-control" name="jml_anggota" placeholder="Masukan Jumlah Anggota">
    </div>
    <div class="form-group">
        <label>Biaya Hosting</label>
        <input type="number" class="form-control" name="biaya_hosting" placeholder="Masukan Biaya Hosting">
    </div>
    <div class="form-group">
        <label>Nama Pic Teknik</label>
        <input type="text" class="form-control" name="pic_teknik" placeholder="Masukan Pic Teknik">
    </div>
    <div class="form-group">
        <label>Syariah</label>
        <select name="syariah" class="form-control select2 m_select2_4">                                
            <option value="Tidak">Tidak</option>
            <option value="Ya">Ya</option>
        </select>
    </div>
    <div class="form-group">
        <label>Level</label>
        <select name="level" class="form-control select2 m_select2_4">                                
            <option value="Pusat">Pusat</option>
            <option value="Cabang">Cabang</option>
        </select>
    </div>
    <div class="form-group">
        <label>Status</label>
        <select name="status" class="form-control select2 m_select2_4">                                
            <option value="Tidak Aktif">Tidak Aktif</option>
            <option value="Aktif">Aktif</option>
        </select>
    </div>
    <div class="form-group">
        <label class="form-control-label">Tanggal Setup</label>
        <div class="input-group m-input-group">
            <input type="text" name="tgl_setup" class="form-control" id="m_datepicker_1" readonly="" placeholder="Select date &amp; time">
            <div class="input-group-prepend"><span class="input-group-text"><i class="la la-calendar-check-o"></i></span></div>
        </div>
    </div>
    <div class="form-group">
        <label>Harga Aplikasi</label>
        <input type="number" class="form-control" name="harga_aplikasi" placeholder="Masukan Harga Aplikasi">
    </div>
    <div class="form-group">
        <label>History</label>
        <input type="text" class="form-control" name="history" placeholder="Masukan History">
    </div>
    <div class="form-group">
        <label>Status Pembayaran</label>
        <input type="text" class="form-control" name="status_pembayaran" placeholder="Masukan Status Pembayaran">
    </div>
    <button type="submit" class="btn btn-primary">Simpan</button>
</form>        

@endsection

resources/views/admin/koperasi/show.blade.php
@extends('layouts.app')
@section('title')
  Daftar Semua Koperasi {{$jenisKoperasi->nama}}
@endsection
@section('isi')
<div class="m-portlet m-portlet--head-lg">
  <div class="m-portlet__head">
    <div class="m-portlet__head-caption">
      <div class="m-portlet__head-title">
        <span class="m-portlet__head-icon">
          <i class="la la-list"></i>
        </span>
        <h3 class="m-portlet__head-text">
          Daftar Semua Koperasi {{$jenisKoperasi->nama}}
        </h3>
      </div>
    </div>
  </div>
  <div class="m-portlet__body">
      @if(session()->has('success'))
      <div class="m-alert m-alert--icon alert m-alert--square alert-success m--margin-bottom-25" role="alert">
        <div class="m-alert__icon">
          <i class="la la-check-circle-o"></i>
        </div>
        <div class="m-alert__text">
          <strong>Berhasil!</strong> {{ session()->get('success') }}
        </div>
        <div class="m-alert__close">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          </button>
        </div>
      </div>
    @endif
    @if(session()->has('danger'))
      <div class="m-alert m-alert--icon alert m-alert--square alert-danger m--margin-bottom-25" role="alert">
        <div class="m-alert__icon">
          <i class="la la-exclamation-circle"></i>
        </div>
        <div class="m-alert__text">
          <strong>Gagal!</strong> {{ session()->get('danger') }}
        </div>
        <div class="m-alert__close">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          </button>
        </div>
      </div>
    @endif
    <div class="list-section">
      @forelse ($jenisKoperasi->koperasi as $item) 
      <div class="list-section__item">
        <div class="section__content image-box">
          <div class="section__desc">
            <h5 class="section__title">{{ $item->nama_institusi }}</h5>
            <div class="section__info">
              <div class="section__info__item sm-text">
                <span class="info__label">Posted By :</span>
                <a href="" class="info__detail m-link">{{ $item->users->name }}</a>
              </div>
            </div>
          </div>
        </div>
        <div class="section__action">
          <div class="list__section__action">
            <a href="{{ url('koperasi/'.$item->id.'/edit')}}" class="btn m-btn btn-success btn-sm m-btn--icon m-btn--air icon-only">
              <span>
                <i class="la la-pencil"></i>
                <span>Edit Koperasi</span>
              </span>
            </a>
            <a href="{{ url('file/'.$item->id) }}" class="btn m-btn btn-info btn-sm m-btn--icon m-btn--pill m-btn--air icon-only">
              <span>
                <i class="la la-file"></i>
                <span>Management File</span>
              </span>
            </a>            
            <a href="#" class="btn m-btn btn-primary btn-sm m-btn--icon m-btn--pill m-btn--air icon-only">
              <span>
                <i class="la la-eye"></i>
                <span>Profil Koperasi</span>
              </span>
            </a>
            <a href="javascript:void(0);" onclick="$(this).find('form').submit();" class="btn m-btn btn-outline-danger btn-sm  m-btn--icon m-btn--pill icon-only m_sweetalert_5">
              <span>
                <i class="la la-trash"></i>
                <span>Delete Koperasi</span>                
              </span>
              <form action="{{ route('koperasi.destroy', $item->id) }}" method="post">
                {{ csrf_field() }}
                {{ method_field('DELETE') }}
              </form>
            </a>
          </div>
        </div>
      </div>
      @empty
      <div class="m-portlet__body">
        <p>Kosong</p>
      </div>        
      @endforelse            
    </div>
  </div>
</div>
@endsection